services:
  axiom-dashboard:
    image: ghcr.io/sunbrolynk/axiom-dashboard:latest
    container_name: axiom-dashboard
    restart: unless-stopped
    ports:
      - "8050:8050"
    environment:
      - AXIOM_API_TOKEN=
      - AXIOM_DATASET=
      - GOOGLE_MAPS_API_KEY=
      - MAXMIND_DB_PATH=/app/backend/data/GeoLite2-City.mmdb
    volumes:
      - ./backend/data:/app/backend/data:ro
